
# /usr/lib/python2.4/site-packages/numbler/server/locale/localtab_en_US.py
# This file is automatically generated. Do not edit.

_lr_method = 'SLR'

_lr_signature = '\xd6P3\xf3.>g\x06\xe6\x8d\xc7,\x07\xabd\xa5'

_lr_action_items = {'$':([75,53,29,20,2,5,56,31,4,7,64,66,61,69,41,42,37,68,25,45,71,10,14,36,24,13,19,1,39,3,57,82,77,65,79,46,50,76,32,67,30,22,9,17,8,6,16,11,18,73,26,62,15,72,70,21,],[-57,-40,-44,-51,-33,-24,-56,-50,-25,-6,-43,-21,-22,-23,-32,-30,-29,-15,-1,-35,-39,-20,-31,-34,-4,-18,-10,-19,-42,-13,-28,-52,-9,-55,-53,-37,-36,-14,0,-49,-3,-5,-11,-28,-17,-2,-16,-27,-7,-8,-26,-54,-45,-41,-38,-12,]),'TIMESEP':([74,17,8,66,],[43,43,33,-21,]),'SPACE':([45,28,2,79,17,37,20,69,78,82,35,9,67,61,31,24,5,14,11,65,76,26,3,23,29,12,74,27,1,21,62,16,36,10,19,68,42,15,8,30,41,57,4,66,13,22,],[-35,58,-33,-53,49,-29,-51,-23,58,-52,58,-11,58,-22,-50,54,-24,-31,-27,-55,-14,-26,-13,52,-44,38,81,55,-19,-12,-54,-16,-34,-20,-10,-15,-30,-45,34,60,-32,-28,-25,-21,40,51,]),'CURRENCY':([0,12,52,23,38,],[27,27,27,27,27,]),'CUSTOMLIT0':([9,76,],[35,-14,]),'CLOCK':([49,34,81,40,],[69,62,69,65,]),'PERCENT':([11,22,4,2,49,37,42,14,17,41,26,57,51,45,36,5,],[-27,50,-25,-33,70,-29,-30,-31,46,-32,-26,-28,71,-35,-34,-24,]),'PLUS':([0,12,23,52,38,],[12,12,12,12,12,]),'DASH':([67,12,17,15,23,28,35,38,0,78,29,52,],[48,23,48,-45,23,48,48,23,23,48,-44,23,]),'LONGMONTH':([23,44,60,49,58,47,0,12,38,52,48,],[15,15,15,-48,-48,-46,15,15,15,15,-47,]),'SHORTMONTH':([52,48,38,12,23,44,60,58,47,0,49,],[29,-47,29,29,29,29,29,-48,-46,29,-48,]),'SLASH':([78,15,35,17,28,67,29,],[47,-45,47,47,47,47,-44,]),'INTEGER':([55,52,0,47,48,44,58,23,54,33,38,27,49,63,80,59,12,60,43,],[57,17,17,-46,-47,67,-48,17,74,61,17,57,-48,79,82,76,17,78,66,]),'EXP':([11,14,17,57,26,],[37,41,42,42,-26,]),'COMMAINT':([0,55,27,52,23,12,38,],[26,26,26,26,26,26,26,]),'FRACTION':([0,27,52,11,12,23,57,55,17,26,38,],[14,14,14,14,14,14,14,14,14,-26,14,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'monthday':([12,23,60,52,0,38,],[9,9,9,9,9,9,]),'medtimeclock':([12,54,0,23,52,38,],[1,1,1,1,1,1,]),'floatdec':([12,0,27,52,17,23,57,55,38,11,],[2,2,2,2,45,2,45,2,2,36,]),'monthyearint':([23,0,60,12,38,52,],[3,3,3,3,3,3,]),'float':([23,12,38,52,27,0,55,],[4,4,4,4,4,4,4,]),'normalint':([52,0,23,38,12,27,55,],[5,5,5,5,5,5,5,]),'month':([52,38,44,23,12,60,0,],[28,28,68,28,28,28,28,]),'currency':([38,52,23,0,12,],[7,7,7,7,7,]),'medtime':([38,0,12,52,23,54,],[8,8,8,8,8,8,]),'longtimeclock':([0,54,38,52,12,23,],[10,10,10,10,10,10,]),'timedate':([38,12,0,23,52,],[6,6,6,6,6,]),'commaint':([55,52,0,27,38,12,23,],[11,11,11,11,11,11,11,]),'longtime':([23,0,54,38,12,52,],[13,13,13,13,13,13,]),'shorttime':([0,54,38,23,12,52,],[16,16,16,16,16,16,]),'percentage':([38,12,23,52,0,],[18,18,18,18,18,]),'formaldate':([12,60,23,38,52,0,],[19,19,19,19,19,19,]),'meddate':([0,52,38,60,23,12,],[20,20,20,20,20,20,]),'datesep':([28,17,67,78,35,],[59,44,80,44,63,]),'monthyear':([12,52,0,38,23,60,],[21,21,21,21,21,21,]),'number':([38,55,27,0,23,52,12,],[22,75,56,22,22,22,22,]),'date':([38,0,12,60,23,52,],[24,24,24,77,24,24,]),'datetime':([38,52,23,0,12,],[25,25,25,25,25,]),'time':([54,23,0,52,38,12,],[73,30,30,30,30,30,]),'shortdate':([60,12,52,0,38,23,],[31,31,31,31,31,31,]),'expression':([52,0,12,38,23,],[72,32,39,64,53,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',55),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',56),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',57),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',58),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',59),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',60),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',61),
  ('datetime',3,'p_datetime','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',66),
  ('timedate',3,'p_timedate','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',71),
  ('date',1,'p_date','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',76),
  ('date',1,'p_date','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',77),
  ('date',1,'p_date','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',78),
  ('date',1,'p_date','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',79),
  ('monthday',3,'p_monthday','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',91),
  ('monthyear',3,'p_monthyear','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',106),
  ('time',1,'p_time','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',120),
  ('time',1,'p_time','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',121),
  ('time',1,'p_time','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',122),
  ('time',1,'p_time','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',123),
  ('time',1,'p_time','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',124),
  ('medtime',3,'p_medtime','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',130),
  ('longtime',3,'p_longtime','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',136),
  ('shorttime',3,'p_short_time','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',143),
  ('number',1,'p_number','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',150),
  ('number',1,'p_number','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',151),
  ('commaint',1,'p_commaint','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',159),
  ('normalint',1,'p_normalint','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',163),
  ('normalint',1,'p_normalint','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',164),
  ('normalint',2,'p_normalint','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',165),
  ('normalint',2,'p_normalint','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',166),
  ('floatdec',1,'p_floatdec','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',175),
  ('floatdec',2,'p_floatdec','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',176),
  ('float',1,'p_float','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',185),
  ('float',2,'p_float','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',186),
  ('float',2,'p_float','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',187),
  ('percentage',2,'p_percentage','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',204),
  ('percentage',2,'p_percentage','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',205),
  ('percentage',3,'p_percentage','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',206),
  ('percentage',3,'p_percentage','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',207),
  ('expression',2,'p_expr_negation','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',213),
  ('expression',3,'p_expr_negation','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',214),
  ('expression',2,'p_expr_positive','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',222),
  ('expression',3,'p_expr_positive','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',223),
  ('month',1,'p_month','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',231),
  ('month',1,'p_month','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',232),
  ('datesep',1,'p_datesep','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',261),
  ('datesep',1,'p_datesep','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',262),
  ('datesep',1,'p_datesep','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',263),
  ('monthyearint',3,'p_monthyearint','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',270),
  ('formaldate',1,'p_formaldate','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',293),
  ('formaldate',1,'p_formaldate','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',294),
  ('shortdate',5,'p_shortdate','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',300),
  ('meddate',4,'p_meddate','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',316),
  ('medtimeclock',3,'p_medtimeclock','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',324),
  ('longtimeclock',3,'p_longtimeclock','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',332),
  ('currency',2,'p_currency','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',339),
  ('currency',3,'p_currency','/usr/lib/python2.4/site-packages/numbler/server/locale/parser_en_US.py',340),
]
