
# /usr/lib/python2.4/site-packages/numbler/server/literaltab.py
# This file is automatically generated. Do not edit.

_lr_method = 'SLR'

_lr_signature = '\\e\x8a\x1f\x18\xc7\xa3U\x94c\xf2a|[\xbc\xb2'

_lr_action_items = {'FRACTION':([0,15,11,23,9,45,22,19,],[17,17,17,17,17,17,-30,17,]),'CLOCK':([59,51,43,15,],[60,56,34,34,]),'PERCENT':([22,4,2,9,37,3,32,17,28,38,15,18,29,45,],[-30,-28,-37,-31,-34,-29,-39,-35,-38,-36,-32,40,-33,-32,]),'SLASH':([48,25,15,50,49,],[31,31,31,31,31,]),'MONTH':([33,12,7,0,51,19,35,56,59,26,11,31,14,60,34,],[50,-22,-21,25,-23,25,-19,-24,-25,25,25,-18,-20,-26,-27,]),'DASH':([15,50,19,25,48,11,0,49,],[35,35,19,35,35,19,19,35,]),'CURRENCY':([15,11,37,4,0,29,22,18,32,28,3,9,19,17,45,38,2,],[-32,23,-34,-28,23,-33,-30,39,-39,-38,-29,-31,23,-35,-32,-36,-37,]),'COLON':([51,15,43,],[55,36,36,]),'PLUS':([0,11,19,],[11,11,11,]),'EXP':([45,17,15,9,22,],[37,38,37,29,-30,]),'INTEGER':([57,20,0,51,13,58,23,54,33,60,11,14,8,7,26,52,36,56,46,49,59,12,55,31,34,35,24,19,53,50,],[-17,43,15,-23,-11,-15,45,58,49,-26,15,-20,-10,-21,48,-13,51,-24,52,-16,-25,-22,59,-18,-27,-19,-12,15,57,-14,]),'COMMAINT':([0,19,23,11,],[22,22,22,22,]),'$':([49,38,56,26,52,47,29,20,2,28,5,58,7,34,42,37,45,10,14,18,24,13,44,1,39,27,12,3,60,57,50,59,41,22,32,30,9,51,40,17,8,6,16,4,15,21,],[-16,-36,-24,-3,-13,-9,-33,-4,-37,-38,-2,-15,-21,-27,-8,-34,-32,-40,-20,-5,-12,-11,-42,-41,-43,0,-22,-29,-26,-17,-14,-25,-45,-30,-39,-46,-31,-23,-44,-35,-10,-6,-7,-28,-32,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'currencyprec':([0,11,19,],[10,10,10,]),'datestr':([0,19,26,11,],[13,13,13,13,]),'floatdec':([15,19,9,23,0,11,45,],[32,2,28,2,2,2,32,]),'datesep':([25,15,48,49,50,],[46,33,33,53,54,]),'datetime':([0,11,19,],[21,21,21,]),'expression':([11,19,0,],[30,41,27,]),'float':([11,19,23,0,],[3,3,3,3,]),'normalint':([0,19,11,23,],[4,4,4,4,]),'strdate':([19,26,0,11,],[24,24,24,24,]),'number':([23,19,0,11,],[44,18,18,18,]),'currency':([0,19,11,],[6,6,6,]),'date':([19,26,11,0,],[20,47,20,20,]),'medtime':([19,20,11,0,],[7,7,7,7,]),'currencypost':([0,19,11,],[1,1,1,]),'longtime':([0,20,19,11,],[12,12,12,12,]),'datenumeric':([26,19,11,0,],[8,8,8,8,]),'time':([11,19,20,0,],[26,26,42,26,]),'shorttime':([20,0,11,19,],[14,14,14,14,]),'percentage':([0,11,19,],[16,16,16,]),'timedate':([19,0,11,],[5,5,5,]),'commaint':([11,0,19,23,],[9,9,9,9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',115),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',116),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',117),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',118),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',119),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',120),
  ('expression',1,'p_all_expressions','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',121),
  ('datetime',2,'p_datetime','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',126),
  ('timedate',2,'p_timedate','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',130),
  ('date',1,'p_date','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',135),
  ('date',1,'p_date','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',136),
  ('date',1,'p_date','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',137),
  ('strdate',3,'p_strdate','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',143),
  ('datestr',3,'p_datestr','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',151),
  ('datestr',5,'p_datestr','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',152),
  ('datenumeric',3,'p_datenumeric','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',160),
  ('datenumeric',5,'p_datenumeric','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',161),
  ('datesep',1,'p_datesep','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',169),
  ('datesep',1,'p_datesep','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',170),
  ('time',1,'p_time','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',175),
  ('time',1,'p_time','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',176),
  ('time',1,'p_time','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',177),
  ('medtime',3,'p_medtime','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',183),
  ('medtime',4,'p_medtime','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',184),
  ('longtime',5,'p_longtime','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',192),
  ('longtime',6,'p_longtime','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',193),
  ('shorttime',2,'p_short_time','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',201),
  ('number',1,'p_number','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',207),
  ('number',1,'p_number','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',208),
  ('commaint',1,'p_commaint','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',213),
  ('normalint',1,'p_normalint','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',217),
  ('normalint',1,'p_normalint','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',218),
  ('normalint',2,'p_normalint','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',219),
  ('normalint',2,'p_normalint','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',220),
  ('floatdec',1,'p_floatdec','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',228),
  ('floatdec',2,'p_floatdec','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',229),
  ('float',1,'p_float','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',234),
  ('float',2,'p_float','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',235),
  ('float',2,'p_float','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',236),
  ('currency',1,'p_currency','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',244),
  ('currency',1,'p_currency','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',245),
  ('currencyprec',2,'p_currencyprec','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',250),
  ('currencypost',2,'p_currencypost','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',258),
  ('percentage',2,'p_percentage','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',266),
  ('expression',2,'p_expr_negation','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',271),
  ('expression',2,'p_expr_positive','/usr/lib/python2.4/site-packages/numbler/server/literal_parser.py',276),
]
